### ISSUE TITLE
builder() cannot be found

### ISSUE THREAD

**Issue by brancyx** [kaiyanghuan/auction-service#1]
When I try to build the project, the builder() can't seem to be found.

Here is the error message:
`java: cannot find symbol
  symbol:   method builder()
  location: class com.ocbc.auctionservice.controllers.responses.ExceptionResponse`

<img width="1401" alt="Screenshot 2021-09-26 at 12 44 43 PM" src="https://user-images.githubusercontent.com/43176177/134794059-ab5706ad-7c03-45ee-a817-f77170035090.png">

**Comment by cjjavellana** [comment]
@brancyx, would you be able to run the command on your command line?
```shell
$ mvn clean package -DskipTests
```

Please run the above command on the same directory where your project pom.xml is located.

**Comment by brancyx** [comment]
I realised the issue is caused by the compiler not supporting Lombok.

Fix (Mac):
- Adding the argument below in the build process VM options:
```
-Djps.track.ap.dependencies=false
```
- Path: 
> Preferences -> Build, Execution, Deployment -> Compiler -> Shared build process VM options

@cjjavellana thanks for your help anyways!
